services:
  test-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5433:5432"

    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data: