"""update url column in media_assets table

Revision ID: 0014fe881909
Revises: 0da353ea221d
Create Date: 2026-08-18 00:59:59.180191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0014fe881909'
down_revision: Union[str, Sequence[str], None] = '0da353ea221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
