"""create director, movie_director tables

Revision ID: 40f5dba1d959
Revises: a348f49b5c3a
Create Date: 2026-07-28 23:11:04.672277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f5dba1d959'
down_revision: Union[str, Sequence[str], None] = 'a348f49b5c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("birthdate >= '1800-01-01'", name='check_director_birthdate'),
    sa.CheckConstraint('length(trim(bio)) <= 1000', name='check_director_bio_length'),
    sa.CheckConstraint('length(trim(name)) > 0', name='check_director_name'),
    sa.CheckConstraint('length(trim(surname)) > 0', name='check_director_surname_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_surname'), 'directors', ['surname'], unique=False)
    op.create_table('movie_director',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_director')
    op.drop_index(op.f('ix_directors_surname'), table_name='directors')
    op.drop_table('directors')
    # ### end Alembic commands ###
