"""add unique constraint (title,release_date) to movies table

Revision ID: 4f0d849a0dbb
Revises: 88b941e0ac7b
Create Date: 2026-08-05 22:22:37.108252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0d849a0dbb'
down_revision: Union[str, Sequence[str], None] = '88b941e0ac7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_movie_title_release_date', 'movies', ['title', 'release_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_movie_title_release_date', 'movies', type_='unique')
    # ### end Alembic commands ###
