"""alter
 character_name column from 55 to 255

Revision ID: 6fae76813b98
Revises: 0014fe881909
Create Date: 2026-08-18 03:45:26.997483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fae76813b98'
down_revision: Union[str, Sequence[str], None] = '0014fe881909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_actor', 'character_name',
               existing_type=sa.VARCHAR(length=55),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_actor', 'character_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=55),
               existing_nullable=False)
    # ### end Alembic commands ###
