"""add deleted_at column to media_assets table

Revision ID: 7dbefd143a3c
Revises: 1bd404ddf8b4
Create Date: 2026-08-13 01:17:43.223184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbefd143a3c'
down_revision: Union[str, Sequence[str], None] = '1bd404ddf8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'deleted_at')
    # ### end Alembic commands ###
