"""add unique constraint on user_id , movie_in for reviews table

Revision ID: 957b1368e684
Revises: 4f0d849a0dbb
Create Date: 2026-08-08 22:09:07.307043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957b1368e684'
down_revision: Union[str, Sequence[str], None] = '4f0d849a0dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_movie_review', 'reviews', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_movie_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
