"""create movies , languages tables

Revision ID: 9db37592769d
Revises: 
Create Date: 2026-07-28 22:46:16.892080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db37592769d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("birthdate >= '1800-01-01'", name='check_actor_birthdate'),
    sa.CheckConstraint('length(trim(bio)) <= 1000', name='check_actor_bio_length'),
    sa.CheckConstraint('length(trim(name)) > 0', name='check_actor_name_length'),
    sa.CheckConstraint('length(trim(surname)) > 0', name='check_actor_surname_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.CheckConstraint('length(trim(code)) = 2', name='check_language_code_length'),
    sa.CheckConstraint('length(trim(name)) > 0', name='check_language_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('duration_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("release_date >= '1895-01-01'::date", name='check_movie_release_date'),
    sa.CheckConstraint('duration_time > 0', name='check_movie_duration_time'),
    sa.CheckConstraint('length(trim(description)) <= 1000', name='check_movie_description_length'),
    sa.CheckConstraint('length(trim(title)) > 0', name='check_movie_title_length'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_language_id'), 'movies', ['language_id'], unique=False)
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('movie_actor',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=55), nullable=False),
    sa.CheckConstraint('length(trim(character_name)) > 0', name='check_actor_character_name_length'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_release_date'), table_name='movies')
    op.drop_index(op.f('ix_movies_language_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('languages')
    op.drop_table('actors')
    # ### end Alembic commands ###
