"""change check bio, description constraint limit from 1000 to 2000 in directors, actors, movies tables, add roles enum

Revision ID: 9f730455a44f
Revises: 6da56ddc37fc
Create Date: 2026-08-15 01:57:44.208362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f730455a44f'
down_revision: Union[str, Sequence[str], None] = '6da56ddc37fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    role_enum = sa.Enum('user', 'admin', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'role',
        existing_type=sa.VARCHAR(length=20),
        type_=role_enum,
        existing_nullable=False,
        postgresql_using="role::role_enum",
    )
    # ### end Alembic commands ###


    op.drop_constraint("check_director_bio_length", "directors", type_="check")
    op.create_check_constraint(
        "check_director_bio_length",
        "directors",
        "length(trim(bio)) <= 2000",
    )

    op.drop_constraint("check_actor_bio_length", "actors", type_="check")
    op.create_check_constraint(
        "check_actor_bio_length",
        "actors",
        "length(trim(bio)) <= 2000",
    )

    op.drop_constraint("check_movie_description_length", "movies", type_="check")
    op.create_check_constraint(
        "check_movie_description_length",
        "movies",
        "length(trim(description)) <= 2000",
    )


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_constraint("check_movie_description_length", "movies", type_="check")
    op.create_check_constraint(
        "check_movie_description_length",
        "movies",
        "length(trim(description)) <= 1000",
    )

    op.drop_constraint("check_actor_bio_length", "actors", type_="check")
    op.create_check_constraint(
        "check_actor_bio_length",
        "actors",
        "length(trim(bio)) <= 1000",
    )

    op.drop_constraint("check_director_bio_length", "directors", type_="check")
    op.create_check_constraint(
        "check_director_bio_length",
        "directors",
        "length(trim(bio)) <= 1000",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'role',
        existing_type=sa.Enum('user', 'admin', name='role_enum'),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    sa.Enum(name='role_enum').drop(op.get_bind(), checkfirst=True)