"""add surname index for actors

Revision ID: a348f49b5c3a
Revises: 6663dc05c091
Create Date: 2026-07-28 23:01:18.331706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a348f49b5c3a'
down_revision: Union[str, Sequence[str], None] = '6663dc05c091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actors_surname'), 'actors', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actors_surname'), table_name='actors')
    # ### end Alembic commands ###
