"""create media_assets table

Revision ID: dd5052317725
Revises: 45a25c5e9153
Create Date: 2026-07-28 23:22:30.016795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5052317725'
down_revision: Union[str, Sequence[str], None] = '45a25c5e9153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=55), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(asset_type)) > 0', name='check_movie_asset_type_length'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_movie_id'), 'media_assets', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_movie_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
